### ISSUE TITLE
Add plugin packets

### ISSUE THREAD

**Issue by hbeni** [bkacjios/Lumble#8]
Hello,
https://github.com/mumble-voip/mumble/pull/3743 will introduce a new plugin framework and with that comes a new packet type in the protocol that allows plugins to communicate to each other.
It would be nice if this packet would be supported in the lua server, so the messages the clients send will be relayed to other clients.

The protobuf definition is [here](https://github.com/Krzmbrzl/mumble/blob/plugin-API/src/Mumble.proto):
```// Used to send plugin messages between clients
message PluginDataTransmission {
	// The session ID of the client this message was sent from
	optional uint32 senderSession = 1;
	// The session IDs of the clients that should receive this message
	repeated uint32 receiverSessions = 2 [packed = true];
	// The data that is sent
	optional bytes data = 3;
	// The ID of the sent data. This will be used by plugins to check whether they will
	// process it or not
	optional string dataID = 4;
}
```

(related to https://github.com/bkacjios/lua-mumble/issues/9)

**Comment by bkacjios** [comment]
Implemented in 9c73ccc14e7768f94f55beedb609fa1959360e7c
